version: "3.7"
services:
  conpot:
    image: yamchah2/conpot:bacnet_fix
    ports:
      - "80:8800" #SCADA UI, http
      - "102:10201" #S7Comm
      - "502:5020" #Modbus
      - "161:16100/udp" #SNMP
      - "47808:47808/udp" #Bacnet
      - "623:6230/udp" #IPMI
      - "21:2121" #FTP
      - "69:6969/udp" #TFTP
      - "44818:44818" #EN/IP
      - "2404:2404" #IEC104, not in default template
    restart: always
  
  gaspot:
    image: rosesecurity/gaspot:v0.1.1
    container_name: gaspot
    ports:
      - "10001:10001"

  